### ISSUE TITLE
Add `logo` to app.json

### ISSUE THREAD

**Issue by crcastle** [fostive/wicked-coolkit-user#15]
Add a `logo` and point to a square image in [app.json](https://github.com/fostive/wicked-coolkit-user/blob/main/app.json).

It will show up here when people click "Make yours"

![CleanShot 2021-01-28 at 13 07 01@2x](https://user-images.githubusercontent.com/275734/106180032-cb960900-6169-11eb-8152-1a0532ec7b8a.png)

**Comment by lynnandtonic** [comment]
@crcastle Can we use this image? https://wickedcoolkit.com/resources/images/og-image.png

**Comment by lynnandtonic** [comment]
@crcastle PR for you here: https://github.com/fostive/wicked-coolkit-user/pull/18
