### ISSUE TITLE
Trading card shows error if no picture or stickers

### ISSUE THREAD

**Issue by crcastle** [fostive/wicked-coolkit-user#29]
A tester reported entering their information in Salesforce without an image or any stickers, then refreshing their Heroku app and getting an error on the trading card.

Try to repro this. It might have been a different issue because this tester had had some oauth issues before this.

**Comment by lukekarrys** [comment]
I think not having an image will fail currently.

**Comment by lukekarrys** [comment]
@crcastle Do you think it would be better to show the error message instructing them to finish setting up their card? Or to display the card with no image?

**Comment by lukekarrys** [comment]
I took a pass at making the card display with no image in this PR https://github.com/fostive/wicked-coolkit/pull/29. Let me know if you have any issues with the code or merging/publishing.
