### ISSUE TITLE
Say somewhere that everything the user is about to create is free

### ISSUE THREAD

**Issue by crcastle** [fostive/wicked-coolkit-user#31]
@raul asked this question. He assumed everything was going to be free, but others may not.

**Comment by lynnandtonic** [comment]
Added "free" to the /getting-started steps here: https://github.com/fostive/wicked-coolkit-user/pull/33

I will also add it to wickedcoolkit.com in a different PR

**Comment by lynnandtonic** [comment]
Other PR: https://github.com/fostive/wickedcoolkit.com/pull/69
