### ISSUE TITLE
Any thoughts to make /getting-started look less intimidating?

### ISSUE THREAD

**Issue by crcastle** [fostive/wicked-coolkit-user#34]
Thought from @raul

> Also, not trying to criticise but the [/getting-started] list looks long intimidating, with the nested steps. I wonder if a wizard-like UI with graphics for each step would make it feel less of a laundry list

@lynnandtonic I know we tried to reduce the number of steps as much as we could, but I wonder if we can visually make `/getting-started` look less intimidating?

**Comment by lynnandtonic** [comment]
Do you think moving the optional steps out of the list would help? I can try a few things.

**Comment by lynnandtonic** [comment]
@crcastle How does this look? (I added it to my open PR): https://github.com/fostive/wicked-coolkit-user/issues/34
