### ISSUE TITLE
Link not working to complete trading card

### ISSUE THREAD

**Issue by spectrethree** [fostive/wicked-coolkit-user#36]
![image](https://user-images.githubusercontent.com/71684035/108267782-7de53e80-7120-11eb-8db6-4dcfeb334a0f.png)

The link from the getting started page to complete the card, it gives me the invalid URL alert, above.

I also tried from my main page, which looks like this: 
![image](https://user-images.githubusercontent.com/71684035/108268145-fba94a00-7120-11eb-8b59-58db934ec8d0.png) and that link just takes me here: 
![image](https://user-images.githubusercontent.com/71684035/108268226-14b1fb00-7121-11eb-971b-1ecc78a03df1.png)

Is there something else I should do?

**Comment by julianduque** [comment]
Hey @spectrethree, 

Did you install the Wicked CoolKit package on your Salesforce DevHub? Can you take a look by clicking at the menu app switcher (9 dots menu below the cloud on the top-left corner), view all, and then see if there is an app called Wicked CoolKit?

**Comment by spectrethree** [comment]
> 
> 
> Hey @spectrethree,
> 
> Did you install the Wicked CoolKit package on your Salesforce DevHub? Can you take a look by clicking at the menu app switcher (9 dots menu below the cloud on the top-left corner), view all, and then see if there is an app called Wicked CoolKit?

Hey @julianduque - it turns out I do not have that installed, although when I click on the link for the instructions to connect heroku and salesforce, it says this - there is no option to allow.

![image](https://user-images.githubusercontent.com/71684035/108398683-243b4d80-71ce-11eb-9a03-02e27e51f1cf.png)

What should I do?

**Comment by julianduque** [comment]
@spectrethree after you deployed the Salesforce App successfully, and clicked "Connect Heroku app to Salesforce", what did you get?

**Comment by spectrethree** [comment]
> 
> 
> @spectrethree after you deployed the Salesforce App successfully, and clicked "Connect Heroku app to Salesforce", what did you get?

![image](https://user-images.githubusercontent.com/71684035/108550610-a6e20c80-72a3-11eb-8a61-a8c988458cb5.png)

**Comment by julianduque** [comment]
@spectrethree ahhh good! So it worked, I missed the banner on the top that says

> "Your Heroku App has been successfully connected to Salesforce!"

Do you think we should make that bigger? more clear? cc @lynnandtonic 

After that, clicking "Complete my card" still takes you to the wrong URL?

**Comment by spectrethree** [comment]
Yup. Video attached.
https://user-images.githubusercontent.com/71684035/108553358-66848d80-72a7-11eb-8410-2bc6ddaa363d.mp4

**Comment by julianduque** [comment]
@spectrethree Thanks for sharing! 

It seems the Wicked Coolkit Salesforce app from Step 2. isn't deployed correctly, can you check if it's there by going to the App Menu. Check the video:

https://user-images.githubusercontent.com/733877/108559862-e885ae00-72c9-11eb-8fa0-c0887ec9efca.mov

**Comment by spectrethree** [comment]
@julianduque Aha! That fixed it!! Now it's working. Thanks so much.

**Comment by julianduque** [comment]
@spectrethree fantastic!!!
